In [ ]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight
from scipy.sparse import load_npz

In [2]:
FILES = {
    "tfidf_cleaned": ("text_representation/TF_IDF/text_representation_cleaned_tfidf.npz", "schemas/fully_cleaned.csv"),
    "tfidf_no_lemma": ("text_representation/TF_IDF/text_representation_tfidf_without_Lemmatization.npz", "schemas/without_lemmatization.csv"),
    "tfidf_no_stop": ("text_representation/TF_IDF/text_representation_tfidf_withoutStopwords_RemovePunctuation.npz", "schemas/without_stopwords_lowercasing_punct.csv"),

    "glove_cleaned": ("text_representation/Glove/text_representation_glove_cleaned.csv", "schemas/fully_cleaned.csv"),
    "glove_no_lemma": ("text_representation/Glove/text_representation_glove_without_Lemmatization.csv", "schemas/without_lemmatization.csv"),
    "glove_no_stop": ("text_representation/Glove/text_representation_glove_withoutStopwords_removePunctuation.csv", "schemas/without_stopwords_lowercasing_punct.csv")
}

## SVM

In [ ]:
for name, (feat_path, label_path) in FILES.items():

    df_labels = pd.read_csv(label_path)

    if feat_path.endswith(".npz"):
        X = load_npz(feat_path)
        y = df_labels["sentiment"]

    else:
        df_feat = pd.read_csv(feat_path)
        df_feat["sentiment"] = df_labels["sentiment"]

        X = df_feat.drop("sentiment", axis=1)
        y = df_feat["sentiment"]

    # # OPTIONAL: alignment safety
    # min_len = min(X.shape[0], len(y))
    # X = X[:min_len]
    # y = y[:min_len]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42
    )

    # ---- class weights FIX ----
    # classes = np.unique(y)
    # weights = compute_class_weight(
    #     class_weight="balanced",
    #     classes=classes,
    #     y=y
    # )
    # class_weights_dict = dict(zip(classes, weights))

    svm = SVC(class_weight="balanced", random_state=42)
    svm.fit(X_train, y_train)
    svm_pred = svm.predict(X_test)

    # ---- saving FIX ----
    output_df = pd.DataFrame({
        "sentiment": y_test,
        "svm_pred": svm_pred
    })

    output_df.to_csv(f"output/svm_predictions_{name}.csv", index=False)


In [4]:
df = pd.read_csv('output/svm_predictions_tfidf_cleaned.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("TF-IDF Cleaned SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.75      0.76      0.76       406
     neutral       0.65      0.67      0.66       414
    positive       0.82      0.78      0.80       429

    accuracy                           0.74      1249
   macro avg       0.74      0.74      0.74      1249
weighted avg       0.74      0.74      0.74      1249

[[310  77  19]
 [ 82 276  56]
 [ 23  72 334]]
TF-IDF Cleaned SVM F1 Score: 0.7373534604128187
TF-IDF Cleaned SVM Precision: 0.7385637288705994
TF-IDF Cleaned SVM Recall: 0.7365892714171337
TF-IDF Cleaned SVM Accuracy Score: 0.7365892714171337


In [5]:
df = pd.read_csv('output/svm_predictions_tfidf_no_lemma.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("TF-IDF No Lemma SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Lemma SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Lemma SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Lemma SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.74      0.77      0.75       406
     neutral       0.65      0.65      0.65       414
    positive       0.81      0.77      0.79       429

    accuracy                           0.73      1249
   macro avg       0.73      0.73      0.73      1249
weighted avg       0.73      0.73      0.73      1249

[[314  70  22]
 [ 88 269  57]
 [ 24  76 329]]
TF-IDF No Lemma SVM F1 Score: 0.7304899247634299
TF-IDF No Lemma SVM Precision: 0.7314202135474529
TF-IDF No Lemma SVM Recall: 0.7301841473178543
TF-IDF No Lemma SVM Accuracy Score: 0.7301841473178543


In [6]:
df = pd.read_csv('output/svm_predictions_tfidf_no_stop.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("TF-IDF No Stopwords SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Stopwords SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Stopwords SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Stopwords SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.74      0.78      0.76       418
     neutral       0.65      0.66      0.65       401
    positive       0.82      0.76      0.79       431

    accuracy                           0.74      1250
   macro avg       0.74      0.73      0.74      1250
weighted avg       0.74      0.74      0.74      1250

[[326  72  20]
 [ 83 265  53]
 [ 29  73 329]]
TF-IDF No Stopwords SVM F1 Score: 0.73671691621807
TF-IDF No Stopwords SVM Precision: 0.7384247303409447
TF-IDF No Stopwords SVM Recall: 0.736
TF-IDF No Stopwords SVM Accuracy Score: 0.736


In [7]:
df = pd.read_csv('output/svm_predictions_glove_cleaned.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("Glove Cleaned SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.64      0.63      0.63       406
     neutral       0.50      0.57      0.53       414
    positive       0.66      0.58      0.61       429

    accuracy                           0.59      1249
   macro avg       0.60      0.59      0.59      1249
weighted avg       0.60      0.59      0.59      1249

[[254 103  49]
 [ 97 237  80]
 [ 46 136 247]]
Glove Cleaned SVM F1 Score: 0.592953421817582
Glove Cleaned SVM Precision: 0.5986428565736809
Glove Cleaned SVM Recall: 0.5908726981585268
Glove Cleaned SVM Accuracy Score: 0.5908726981585268


In [8]:
df = pd.read_csv('output/svm_predictions_glove_no_lemma.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("Glove No Lemma SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove No Lemma SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove No Lemma SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove No Lemma SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.63      0.62      0.63       406
     neutral       0.50      0.57      0.53       414
    positive       0.67      0.58      0.62       429

    accuracy                           0.59      1249
   macro avg       0.60      0.59      0.59      1249
weighted avg       0.60      0.59      0.59      1249

[[252 108  46]
 [100 236  78]
 [ 48 131 250]]
Glove No Lemma SVM F1 Score: 0.5931190891727796
Glove No Lemma SVM Precision: 0.5990691252692556
Glove No Lemma SVM Recall: 0.5908726981585268
Glove No Lemma SVM Accuracy Score: 0.5908726981585268


In [9]:
df = pd.read_csv('output/svm_predictions_glove_no_stop.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("Glove No Stopwords SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove No Stopwords SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove No Stopwords SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove No Stopwords SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.57      0.60      0.59       418
     neutral       0.44      0.55      0.48       401
    positive       0.72      0.51      0.60       431

    accuracy                           0.55      1250
   macro avg       0.58      0.55      0.56      1250
weighted avg       0.58      0.55      0.56      1250

[[252 132  34]
 [132 219  50]
 [ 59 152 220]]
Glove No Stopwords SVM F1 Score: 0.5575890842242357
Glove No Stopwords SVM Precision: 0.5794217064253425
Glove No Stopwords SVM Recall: 0.5528
Glove No Stopwords SVM Accuracy Score: 0.5528


## Linear Regression

In [10]:
for name, (feat_path, label_path) in FILES.items():

    df_labels = pd.read_csv(label_path)

    if feat_path.endswith(".npz"):
        X = load_npz(feat_path)
        y = df_labels["sentiment"]

    else:
        df_feat = pd.read_csv(feat_path)
        df_feat["sentiment"] = df_labels["sentiment"]

        X = df_feat.drop("sentiment", axis=1)
        y = df_feat["sentiment"]

    mapping = {
    "negative": -1,
    "neutral": 0,
    "positive": 1
    }

    y = y.map(mapping)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42
    )

    # ---- class weights FIX ----
    # classes = np.unique(y)
    # weights = compute_class_weight(
    #     class_weight="balanced",
    #     classes=classes,
    #     y=y
    # )
    # class_weights_dict = dict(zip(classes, weights))
    # sample_weights = y.map(class_weights_dict)
    
    
    ln = LinearRegression()
    ln.fit(X_train, y_train)
    ln_pred = ln.predict(X_test)
    
    def to_class(x):
        if x < -0.5:
            return -1
        elif x > 0.5:
            return 1
        else:
            return 0
    
    y_test = y_test.reset_index(drop=True)
    ln_pred_class = np.vectorize(to_class)(ln_pred)
    ln_pred_class = pd.Series(ln_pred_class).reset_index(drop=True)
    # reverse_mapping
    ln_pred_class = ln_pred_class.map({-1: "negative", 0: "neutral", 1: "positive"})
    y_test_class = y_test.map({-1: "negative", 0: "neutral", 1: "positive"})
    # ---- saving FIX ----
    output_df = pd.DataFrame({
        "sentiment": y_test_class,
        "ln_pred_class": ln_pred_class
    })

    output_df.to_csv(f"output/ln_predictions_{name}.csv", index=False)



In [11]:
df = pd.read_csv('output/ln_predictions_tfidf_cleaned.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("TF-IDF Cleaned Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.54      0.50      0.52       406
     neutral       0.42      0.39      0.40       414
    positive       0.57      0.64      0.60       429

    accuracy                           0.51      1249
   macro avg       0.51      0.51      0.51      1249
weighted avg       0.51      0.51      0.51      1249

[[205 119  82]
 [125 160 129]
 [ 51 102 276]]
TF-IDF Cleaned Linear Regression F1 Score: 0.5097498783486797
TF-IDF Cleaned Linear Regression Precision: 0.5087582664017464
TF-IDF Cleaned Linear Regression Recall: 0.5132105684547638
TF-IDF Cleaned Linear Regression Accuracy Score: 0.5132105684547638


In [12]:
df = pd.read_csv('output/ln_predictions_tfidf_no_lemma.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("TF-IDF No Lemma Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF No Lemma Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF No Lemma Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF No Lemma Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.56      0.54      0.55       406
     neutral       0.42      0.39      0.41       414
    positive       0.56      0.61      0.58       429

    accuracy                           0.52      1249
   macro avg       0.51      0.52      0.51      1249
weighted avg       0.51      0.52      0.51      1249

[[220 103  83]
 [127 162 125]
 [ 45 121 263]]
TF-IDF No Lemma Linear Regression F1 Score: 0.5142164257721967
TF-IDF No Lemma Linear Regression Precision: 0.5133356356241532
TF-IDF No Lemma Linear Regression Recall: 0.5164131305044035
TF-IDF No Lemma Linear Regression Accuracy Score: 0.5164131305044035


In [13]:
df = pd.read_csv('output/ln_predictions_tfidf_no_stop.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("TF-IDF No Stopwords Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF No Stopwords Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF No Stopwords Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF No Stopwords Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.57      0.56      0.57       418
     neutral       0.42      0.42      0.42       401
    positive       0.58      0.57      0.58       431

    accuracy                           0.52      1250
   macro avg       0.52      0.52      0.52      1250
weighted avg       0.52      0.52      0.52      1250

[[236 115  67]
 [119 170 112]
 [ 62 122 247]]
TF-IDF No Stopwords Linear Regression F1 Score: 0.5227690656041337
TF-IDF No Stopwords Linear Regression Precision: 0.523167092615142
TF-IDF No Stopwords Linear Regression Recall: 0.5224
TF-IDF No Stopwords Linear Regression Accuracy Score: 0.5224


In [14]:
df = pd.read_csv('output/ln_predictions_glove_cleaned.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove Cleaned Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.73      0.23      0.35       406
     neutral       0.37      0.88      0.52       414
    positive       0.79      0.25      0.38       429

    accuracy                           0.45      1249
   macro avg       0.63      0.45      0.42      1249
weighted avg       0.63      0.45      0.42      1249

[[ 95 303   8]
 [ 29 365  20]
 [  7 316 106]]
Glove Cleaned Linear Regression F1 Score: 0.4174314692360413
Glove Cleaned Linear Regression Precision: 0.6303865196493083
Glove Cleaned Linear Regression Recall: 0.45316253002401924
Glove Cleaned Linear Regression Accuracy Score: 0.45316253002401924


In [15]:
df = pd.read_csv('output/ln_predictions_glove_no_lemma.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove No Lemma Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Lemma Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Lemma Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Lemma Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.72      0.23      0.35       406
     neutral       0.38      0.90      0.53       414
    positive       0.82      0.25      0.38       429

    accuracy                           0.46      1249
   macro avg       0.64      0.46      0.42      1249
weighted avg       0.64      0.46      0.42      1249

[[ 95 301  10]
 [ 29 371  14]
 [  8 315 106]]
Glove No Lemma Linear Regression F1 Score: 0.4206116551997614
Glove No Lemma Linear Regression Precision: 0.6386020744384031
Glove No Lemma Linear Regression Recall: 0.45796637309847876
Glove No Lemma Linear Regression Accuracy Score: 0.45796637309847876


In [16]:
df = pd.read_csv('output/ln_predictions_glove_no_stop.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove No Stopwords Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.70      0.21      0.32       418
     neutral       0.36      0.90      0.51       401
    positive       0.81      0.23      0.36       431

    accuracy                           0.44      1250
   macro avg       0.62      0.45      0.40      1250
weighted avg       0.63      0.44      0.40      1250

[[ 88 322   8]
 [ 27 359  15]
 [ 10 322  99]]
Glove No Stopwords Linear Regression F1 Score: 0.3958979286471559
Glove No Stopwords Linear Regression Precision: 0.6300370531160616
Glove No Stopwords Linear Regression Recall: 0.4368
Glove No Stopwords Linear Regression Accuracy Score: 0.4368
