In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, RandomizedSearchCV
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score, mean_squared_error, make_scorer
import warnings
from sklearn.utils.class_weight import compute_class_weight
from scipy.sparse import load_npz
from scipy.stats import loguniform
warnings.filterwarnings('ignore')

## Before

In [2]:
df = pd.read_csv('output/svm_predictions_tfidf_cleaned.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("TF-IDF Cleaned SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.67      0.45      0.53       148
     neutral       0.59      0.64      0.61       316
    positive       0.85      0.88      0.86       923

    accuracy                           0.78      1387
   macro avg       0.70      0.65      0.67      1387
weighted avg       0.77      0.78      0.77      1387

[[ 66  40  42]
 [ 18 201  97]
 [ 15 100 808]]
TF-IDF Cleaned SVM F1 Score: 0.7715030007977556
TF-IDF Cleaned SVM Precision: 0.7732179520972821
TF-IDF Cleaned SVM Recall: 0.7750540735400144
TF-IDF Cleaned SVM Accuracy Score: 0.7750540735400144


In [3]:
df = pd.read_csv('output/svm_predictions_glove_cleaned.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("Glove Cleaned SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.33      0.58      0.42       148
     neutral       0.34      0.56      0.42       316
    positive       0.85      0.57      0.68       923

    accuracy                           0.57      1387
   macro avg       0.51      0.57      0.51      1387
weighted avg       0.68      0.57      0.59      1387

[[ 86  40  22]
 [ 69 176  71]
 [102 297 524]]
Glove Cleaned SVM F1 Score: 0.594917027620264
Glove Cleaned SVM Precision: 0.6790305483259937
Glove Cleaned SVM Recall: 0.5666906993511175
Glove Cleaned SVM Accuracy Score: 0.5666906993511175


In [5]:
df = pd.read_csv('output/ln_predictions_tfidf_cleaned.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("TF-IDF Cleaned Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.13      0.54      0.21       186
     neutral       0.54      0.09      0.16       394
    positive       0.69      0.54      0.61      1153

    accuracy                           0.44      1733
   macro avg       0.45      0.39      0.33      1733
weighted avg       0.60      0.44      0.46      1733

[[101   6  79]
 [159  36 199]
 [500  25 628]]
TF-IDF Cleaned Linear Regression F1 Score: 0.4642747221382166
TF-IDF Cleaned Linear Regression Precision: 0.5975935525760113
TF-IDF Cleaned Linear Regression Recall: 0.4414310444316214
TF-IDF Cleaned Linear Regression Accuracy Score: 0.44143104443162146


In [6]:
df = pd.read_csv('output/ln_predictions_glove_cleaned.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove Cleaned Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.64      0.05      0.09       186
     neutral       0.33      0.65      0.43       394
    positive       0.84      0.67      0.75      1153

    accuracy                           0.60      1733
   macro avg       0.60      0.46      0.42      1733
weighted avg       0.70      0.60      0.60      1733

[[  9 156  21]
 [  5 257 132]
 [  0 377 776]]
Glove Cleaned Linear Regression F1 Score: 0.6043121014707409
Glove Cleaned Linear Regression Precision: 0.698704461147419
Glove Cleaned Linear Regression Recall: 0.601269474899019
Glove Cleaned Linear Regression Accuracy Score: 0.601269474899019


In [7]:
df = pd.read_csv('output/ln_predictions_glove_no_stop.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove No Stopwords Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.45      0.03      0.05       198
     neutral       0.32      0.64      0.43       391
    positive       0.83      0.68      0.74      1145

    accuracy                           0.59      1734
   macro avg       0.53      0.45      0.41      1734
weighted avg       0.67      0.59      0.59      1734

[[  5 170  23]
 [  3 251 137]
 [  3 368 774]]
Glove No Stopwords Linear Regression F1 Score: 0.5930614041123072
Glove No Stopwords Linear Regression Precision: 0.6708425345986876
Glove No Stopwords Linear Regression Recall: 0.5940023068050749
Glove No Stopwords Linear Regression Accuracy Score: 0.5940023068050749


## After

### SVM with Glove Cleaned

In [17]:

df_feat = pd.read_csv("text_representation/Glove/text_representation_glove_cleaned.csv")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

# Merge features and labels
df_feat["sentiment"] = df_labels["sentiment"]

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.01, 0.1, 1],
    "kernel": ["rbf", "linear"]
}

classes = np.unique(y)
weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)
class_weights_dict = dict(zip(classes, weights))

grid = GridSearchCV(
    SVC(class_weight=class_weights_dict),
    param_grid,
    scoring="f1_macro",
    cv=5
)

grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best F1:", grid.best_score_)

Best params: {'C': 1, 'gamma': 1, 'kernel': 'rbf'}
Best F1: 0.5721507160585054


In [23]:
df_feat = pd.read_csv("text_representation/Glove/text_representation_glove_cleaned.csv")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

# Merge features and labels
df_feat["sentiment"] = df_labels["sentiment"]

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

classes = np.unique(y)
weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)
class_weights_dict = dict(zip(classes, weights))

# -------- SVM --------
svm = SVC(class_weight=class_weights_dict, C=1, gamma=1, kernel="rbf")  # Use best params from GridSearchCV
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)

print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

    negative       0.41      0.63      0.49       186
     neutral       0.41      0.57      0.48       394
    positive       0.86      0.67      0.75      1153

    accuracy                           0.64      1733
   macro avg       0.56      0.62      0.58      1733
weighted avg       0.71      0.64      0.66      1733



In [24]:
print("Glove Cleaned SVM F1 Score:", f1_score(y_test, svm_pred, average='weighted'))
print("Glove Cleaned SVM Precision:", precision_score(y_test, svm_pred, average='weighted'))
print("Glove Cleaned SVM Recall:", recall_score(y_test, svm_pred, average='weighted'))
print("Glove Cleaned SVM Accuracy Score:", accuracy_score(y_test, svm_pred))    

Glove Cleaned SVM F1 Score: 0.6624806304345088
Glove Cleaned SVM Precision: 0.706925097804732
Glove Cleaned SVM Recall: 0.6433929601846509
Glove Cleaned SVM Accuracy Score: 0.6433929601846509


### SVM with tf-idf Cleaned

In [47]:
X = load_npz("text_representation/TF_IDF/text_representation_cleaned_tfidf.npz")
X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.01, 0.1, 1],
    "kernel": ["rbf"]
}

classes = np.unique(y)
weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)
class_weights_dict = dict(zip(classes, weights))


# grid = GridSearchCV(
#     SVC(class_weight=class_weights_dict),
#     param_grid,
#     scoring="f1_macro",
#     cv=5,
#     n_jobs=-1
# )

# grid.fit(X_train, y_train)

# print("Best params:", grid.best_params_)
# print("Best F1:", grid.best_score_)



# param_dist = {
#     "C": loguniform(1e-2, 1e2),     # better than [0.1,1,10]
#     "gamma": loguniform(1e-4, 1),
#     "kernel": ["rbf"]
# }

random_search = RandomizedSearchCV(
    SVC(class_weight=class_weights_dict),
    param_distributions=param_grid,
    n_iter=20,              # 🔥 controls speed (try 20–30)
    scoring="f1_weighted",
    cv=3,                   # 🔥 reduce from 5 → 3
    verbose=2,
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train, y_train)

print("Best params:", random_search.best_params_)
print("Best F1:", random_search.best_score_)

Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV] END .....................C=0.1, gamma=scale, kernel=rbf; total time=  46.3s
[CV] END .....................C=0.1, gamma=scale, kernel=rbf; total time=  47.8s
[CV] END .....................C=0.1, gamma=scale, kernel=rbf; total time=  49.7s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=  49.8s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=  40.3s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=  44.8s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  43.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  49.3s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  42.9s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=  42.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=  40.3s
[CV] END .........................C=0.1, gamma=1

In [50]:
X = load_npz("text_representation/TF_IDF/text_representation_cleaned_tfidf.npz")
X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/fully_cleaned.csv")
y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


classes = np.unique(y)
weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)
class_weights_dict = dict(zip(classes, weights))

# -------- SVM --------
svm_tfidf = SVC(class_weight=class_weights_dict)  # Use best params from GridSearchCV
svm_tfidf.fit(X_train, y_train)
svm_tfidf_pred = svm_tfidf.predict(X_test)

print(classification_report(y_test, svm_tfidf_pred))

              precision    recall  f1-score   support

    negative       0.67      0.45      0.53       148
     neutral       0.59      0.63      0.61       316
    positive       0.85      0.88      0.86       923

    accuracy                           0.77      1387
   macro avg       0.70      0.65      0.67      1387
weighted avg       0.77      0.77      0.77      1387



In [51]:
print("TF-IDF Cleaned SVM F1 Score:", f1_score(y_test, svm_tfidf_pred, average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(y_test, svm_tfidf_pred, average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(y_test, svm_tfidf_pred, average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(y_test, svm_tfidf_pred))   

TF-IDF Cleaned SVM F1 Score: 0.7707135390470595
TF-IDF Cleaned SVM Precision: 0.7723439096829171
TF-IDF Cleaned SVM Recall: 0.7743330930064888
TF-IDF Cleaned SVM Accuracy Score: 0.7743330930064888


### Linear Regression with TF-IDF Cleaned

In [29]:
df_feat = pd.read_csv("text_representation/TF_IDF/text_representation_cleaned_tfidf.xls")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

mapping = {
    "negative": -1,
    "neutral": 0,
    "positive": 1
    }
df_feat["sentiment"] = df_labels["sentiment"]
df_feat["sentiment"] = df_feat["sentiment"].map(mapping)

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define model
ln_reg = LinearRegression()

# Define parameter grid
param_grid = {
    "fit_intercept": [True, False],
    "positive": [True, False]
}

# Use regression metric
scorer = make_scorer(mean_squared_error, greater_is_better=False)

# Grid Search
grid = GridSearchCV(
    estimator=ln_reg,
    param_grid=param_grid,
    scoring=scorer,
    cv=5,
    n_jobs=-1,
    verbose=2
)

# Fit on training data only
grid.fit(X_train, y_train)

# Best model
best_model = grid.best_estimator_

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best Params: {'fit_intercept': True, 'positive': False}
Best CV Score: -0.5006255009898367


In [30]:
df_feat = pd.read_csv("text_representation/TF_IDF/text_representation_cleaned_tfidf.xls")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")
# Merge features and labels
mapping = {
"negative": -1,
"neutral": 0,
"positive": 1
}
df_feat["sentiment"] = df_labels["sentiment"]
df_feat["sentiment"] = df_feat["sentiment"].map(mapping)

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# -------- Linear Regression --------
ln_reg = LinearRegression(fit_intercept=True, positive=False)  # Use best params from GridSearchCV
ln_reg.fit(X_train, y_train)
ln_pred = ln_reg.predict(X_test)
def convert_to_class(x):
    if x > 0.5:
        return "positive"
    elif x < -0.5:
        return "negative"
    else:
        return "neutral"

ln_pred_class = [convert_to_class(x) for x in ln_pred]
y_test_class = [convert_to_class(x) for x in y_test]


print(classification_report(y_test_class, ln_pred_class))

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         2
     neutral       1.00      0.33      0.50         3
    positive       0.56      1.00      0.71         5

    accuracy                           0.60        10
   macro avg       0.52      0.44      0.40        10
weighted avg       0.58      0.60      0.51        10



In [31]:
print("TF-IDF Cleaned Linear regression F1 Score:,", f1_score(y_test_class, ln_pred_class, average='weighted'))
print("TF-IDF Cleaned Linear regression Precision:", precision_score(y_test_class, ln_pred_class, average='weighted'))
print("TF-IDF Cleaned Linear regression Recall:", recall_score(y_test_class, ln_pred_class, average='weighted'))
print("TF-IDF Cleaned Linear regression Accuracy Score:", accuracy_score(y_test_class, ln_pred_class))

TF-IDF Cleaned Linear regression F1 Score:, 0.5071428571428571
TF-IDF Cleaned Linear regression Precision: 0.5777777777777777
TF-IDF Cleaned Linear regression Recall: 0.6
TF-IDF Cleaned Linear regression Accuracy Score: 0.6


In [52]:
import pickle
model_path = "model/SVM_tfidf_cleaned.pkl"
with open(model_path, "wb") as f:
    pickle.dump(svm_tfidf, f)
print(f"Saved model to {model_path}")

Saved model to model/SVM_tfidf_cleaned.pkl
