In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, RandomizedSearchCV
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score, mean_squared_error, make_scorer
import warnings
from sklearn.utils.class_weight import compute_class_weight
from scipy.sparse import load_npz
from scipy.stats import loguniform
warnings.filterwarnings('ignore')

## Before

In [2]:
df = pd.read_csv('output/svm_predictions_tfidf_cleaned.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("TF-IDF Cleaned SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.75      0.76      0.76       406
     neutral       0.65      0.67      0.66       414
    positive       0.82      0.78      0.80       429

    accuracy                           0.74      1249
   macro avg       0.74      0.74      0.74      1249
weighted avg       0.74      0.74      0.74      1249

[[310  77  19]
 [ 82 276  56]
 [ 23  72 334]]
TF-IDF Cleaned SVM F1 Score: 0.7373534604128187
TF-IDF Cleaned SVM Precision: 0.7385637288705994
TF-IDF Cleaned SVM Recall: 0.7365892714171337
TF-IDF Cleaned SVM Accuracy Score: 0.7365892714171337


In [34]:
df = pd.read_csv('output/svm_predictions_tfidf_no_stop.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("TF-IDF No Stopwords SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Stopwords SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Stopwords SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("TF-IDF No Stopwords SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.74      0.78      0.76       418
     neutral       0.65      0.66      0.65       401
    positive       0.82      0.76      0.79       431

    accuracy                           0.74      1250
   macro avg       0.74      0.73      0.74      1250
weighted avg       0.74      0.74      0.74      1250

[[326  72  20]
 [ 83 265  53]
 [ 29  73 329]]
TF-IDF No Stopwords SVM F1 Score: 0.73671691621807
TF-IDF No Stopwords SVM Precision: 0.7384247303409447
TF-IDF No Stopwords SVM Recall: 0.736
TF-IDF No Stopwords SVM Accuracy Score: 0.736


In [3]:
df = pd.read_csv('output/svm_predictions_glove_cleaned.csv')
print(classification_report(df['sentiment'], df['svm_pred']))
print(confusion_matrix(df['sentiment'], df['svm_pred']))
print("Glove Cleaned SVM F1 Score:", f1_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Precision:", precision_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Recall:", recall_score(df['sentiment'], df['svm_pred'], average='weighted'))
print("Glove Cleaned SVM Accuracy Score:", accuracy_score(df['sentiment'], df['svm_pred']))

              precision    recall  f1-score   support

    negative       0.64      0.63      0.63       406
     neutral       0.50      0.57      0.53       414
    positive       0.66      0.58      0.61       429

    accuracy                           0.59      1249
   macro avg       0.60      0.59      0.59      1249
weighted avg       0.60      0.59      0.59      1249

[[254 103  49]
 [ 97 237  80]
 [ 46 136 247]]
Glove Cleaned SVM F1 Score: 0.592953421817582
Glove Cleaned SVM Precision: 0.5986428565736809
Glove Cleaned SVM Recall: 0.5908726981585268
Glove Cleaned SVM Accuracy Score: 0.5908726981585268


In [4]:
df = pd.read_csv('output/ln_predictions_tfidf_cleaned.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("TF-IDF Cleaned Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("TF-IDF Cleaned Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.54      0.50      0.52       406
     neutral       0.42      0.39      0.40       414
    positive       0.57      0.64      0.60       429

    accuracy                           0.51      1249
   macro avg       0.51      0.51      0.51      1249
weighted avg       0.51      0.51      0.51      1249

[[205 119  82]
 [125 160 129]
 [ 51 102 276]]
TF-IDF Cleaned Linear Regression F1 Score: 0.5097498783486797
TF-IDF Cleaned Linear Regression Precision: 0.5087582664017464
TF-IDF Cleaned Linear Regression Recall: 0.5132105684547638
TF-IDF Cleaned Linear Regression Accuracy Score: 0.5132105684547638


In [5]:
df = pd.read_csv('output/ln_predictions_glove_cleaned.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove Cleaned Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove Cleaned Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.73      0.23      0.35       406
     neutral       0.37      0.88      0.52       414
    positive       0.79      0.25      0.38       429

    accuracy                           0.45      1249
   macro avg       0.63      0.45      0.42      1249
weighted avg       0.63      0.45      0.42      1249

[[ 95 303   8]
 [ 29 365  20]
 [  7 316 106]]
Glove Cleaned Linear Regression F1 Score: 0.4174314692360413
Glove Cleaned Linear Regression Precision: 0.6303865196493083
Glove Cleaned Linear Regression Recall: 0.45316253002401924
Glove Cleaned Linear Regression Accuracy Score: 0.45316253002401924


In [6]:
df = pd.read_csv('output/ln_predictions_glove_no_stop.csv')
print(classification_report(df['sentiment'], df['ln_pred_class']))
print(confusion_matrix(df['sentiment'], df['ln_pred_class']))
print("Glove No Stopwords Linear Regression F1 Score:", f1_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Precision:", precision_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Recall:", recall_score(df['sentiment'], df['ln_pred_class'], average='weighted'))
print("Glove No Stopwords Linear Regression Accuracy Score:", accuracy_score(df['sentiment'], df['ln_pred_class']))

              precision    recall  f1-score   support

    negative       0.70      0.21      0.32       418
     neutral       0.36      0.90      0.51       401
    positive       0.81      0.23      0.36       431

    accuracy                           0.44      1250
   macro avg       0.62      0.45      0.40      1250
weighted avg       0.63      0.44      0.40      1250

[[ 88 322   8]
 [ 27 359  15]
 [ 10 322  99]]
Glove No Stopwords Linear Regression F1 Score: 0.3958979286471559
Glove No Stopwords Linear Regression Precision: 0.6300370531160616
Glove No Stopwords Linear Regression Recall: 0.4368
Glove No Stopwords Linear Regression Accuracy Score: 0.4368


## After

### SVM with Glove Cleaned

In [8]:

df_feat = pd.read_csv("text_representation/Glove/text_representation_glove_cleaned.csv")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

# Merge features and labels
df_feat["sentiment"] = df_labels["sentiment"]

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.01, 0.1, 1],
    "kernel": ["rbf", "linear"]
}

# classes = np.unique(y)
# weights = compute_class_weight(
#     class_weight="balanced",
#     classes=classes,
#     y=y
# )
# class_weights_dict = dict(zip(classes, weights))

grid = GridSearchCV(
    SVC(class_weight="balanced"),
    param_grid,
    scoring="f1_macro",
    cv=5
)

grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best F1:", grid.best_score_)

Best params: {'C': 1, 'gamma': 1, 'kernel': 'rbf'}
Best F1: 0.6181128623323764


In [9]:
df_feat = pd.read_csv("text_representation/Glove/text_representation_glove_cleaned.csv")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

# Merge features and labels
df_feat["sentiment"] = df_labels["sentiment"]

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

classes = np.unique(y)
weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)
class_weights_dict = dict(zip(classes, weights))

# -------- SVM --------
svm = SVC(class_weight=class_weights_dict, C=1, gamma=1, kernel="rbf")  # Use best params from GridSearchCV
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)

print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

    negative       0.64      0.70      0.67       406
     neutral       0.55      0.55      0.55       414
    positive       0.71      0.65      0.68       429

    accuracy                           0.63      1249
   macro avg       0.63      0.63      0.63      1249
weighted avg       0.63      0.63      0.63      1249



In [10]:
print("Glove Cleaned SVM F1 Score:", f1_score(y_test, svm_pred, average='weighted'))
print("Glove Cleaned SVM Precision:", precision_score(y_test, svm_pred, average='weighted'))
print("Glove Cleaned SVM Recall:", recall_score(y_test, svm_pred, average='weighted'))
print("Glove Cleaned SVM Accuracy Score:", accuracy_score(y_test, svm_pred))    

Glove Cleaned SVM F1 Score: 0.6333884490196404
Glove Cleaned SVM Precision: 0.6349217050652776
Glove Cleaned SVM Recall: 0.633306645316253
Glove Cleaned SVM Accuracy Score: 0.633306645316253


### SVM with tf-idf Cleaned

In [28]:
X = load_npz("text_representation/TF_IDF/text_representation_cleaned_tfidf.npz")
# X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.01, 0.1, 1, 10],
    "kernel": ["rbf"]
}

# classes = np.unique(y)
# weights = compute_class_weight(
#     class_weight="balanced",
#     classes=classes,
#     y=y
# )
# class_weights_dict = dict(zip(classes, weights))


grid = GridSearchCV(
    SVC(class_weight="balanced"),
    param_grid,
    scoring="f1_weighted",
    cv=5,
    n_jobs=-1,
    verbose=3
)

grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best F1:", grid.best_score_)



# param_dist = {
#     "C": loguniform(1e-2, 1e2),     # better than [0.1,1,10]
#     "gamma": loguniform(1e-4, 1),
#     "kernel": ["rbf"]
# }

# random_search = RandomizedSearchCV(
#     SVC(class_weight=class_weights_dict),
#     param_distributions=param_grid,
#     n_iter=20,              # 🔥 controls speed (try 20–30)
#     scoring="f1_weighted",
#     cv=3,                   # 🔥 reduce from 5 → 3
#     verbose=2,
#     n_jobs=-1,
#     random_state=42
# )

# random_search.fit(X_train, y_train)

# print("Best params:", random_search.best_params_)
# print("Best F1:", random_search.best_score_)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV 1/5] END .............................C=0.1;, score=0.718 total time=   0.2s
[CV 5/5] END .............................C=0.1;, score=0.686 total time=   0.4s
[CV 4/5] END .............................C=0.1;, score=0.694 total time=   0.1s
[CV 1/5] END ...............................C=1;, score=0.697 total time=   0.3s
[CV 2/5] END ...............................C=1;, score=0.691 total time=   0.4s
[CV 3/5] END ...............................C=1;, score=0.711 total time=   0.5s
[CV 2/5] END .............................C=0.1;, score=0.701 total time=   0.4s
[CV 4/5] END ...............................C=1;, score=0.693 total time=   0.3s
[CV 5/5] END ...............................C=1;, score=0.691 total time=   0.9s
[CV 3/5] END .............................C=0.1;, score=0.726 total time=   0.1s
[CV 1/5] END ..............................C=10;, score=0.676 total time=   1.2s
[CV 5/5] END ..............................C=10;,

In [30]:
X = load_npz("text_representation/TF_IDF/text_representation_cleaned_tfidf.npz")
# X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/fully_cleaned.csv")
y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


# classes = np.unique(y)
# weights = compute_class_weight(
#     class_weight="balanced",
#     classes=classes,
#     y=y
# )
# class_weights_dict = dict(zip(classes, weights))

# -------- SVM --------
svm_tfidf = SVC(class_weight="balanced")  # Use best params from GridSearchCV
svm_tfidf.fit(X_train, y_train)
svm_tfidf_pred = svm_tfidf.predict(X_test)

print(classification_report(y_test, svm_tfidf_pred))

              precision    recall  f1-score   support

    negative       0.75      0.76      0.76       406
     neutral       0.65      0.67      0.66       414
    positive       0.82      0.78      0.80       429

    accuracy                           0.74      1249
   macro avg       0.74      0.74      0.74      1249
weighted avg       0.74      0.74      0.74      1249



In [32]:
print("TF-IDF Cleaned SVM F1 Score:", f1_score(y_test, svm_tfidf_pred, average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(y_test, svm_tfidf_pred, average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(y_test, svm_tfidf_pred, average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(y_test, svm_tfidf_pred))   

TF-IDF Cleaned SVM F1 Score: 0.7373534604128187
TF-IDF Cleaned SVM Precision: 0.7385637288705994
TF-IDF Cleaned SVM Recall: 0.7365892714171337
TF-IDF Cleaned SVM Accuracy Score: 0.7365892714171337


### SVM with tf-idf with stop words, lowercase, and punctuation

In [36]:
X = load_npz("text_representation/TF_IDF/text_representation_tfidf_withoutStopwords_RemovePunctuation.npz")
# X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/without_stopwords_lowercasing_punct.csv")

y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.01, 0.1, 1],
    "kernel": ["rbf"]
}


grid = GridSearchCV(
    SVC(class_weight="balanced"),
    param_grid,
    scoring="f1_weighted",
    cv=5,
    n_jobs=-1,
    verbose=3
)

grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best F1:", grid.best_score_)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 4/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.321 total time=  46.0s
[CV 2/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.231 total time=  50.9s
[CV 1/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.344 total time=  49.9s
[CV 3/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.254 total time=  49.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.167 total time=  42.5s
[CV 5/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.333 total time=  46.9s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.167 total time=  47.7s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.167 total time=  48.7s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.171 total time=  44.3s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.171 total time=  50.1s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.167 total time=  47.3s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;

In [37]:
X = load_npz("text_representation/TF_IDF/text_representation_tfidf_withoutStopwords_RemovePunctuation.npz")
# X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/without_stopwords_lowercasing_punct.csv")
y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# -------- SVM --------
svm_tfidf_withoutStopwords_RemovePunctuation = SVC(class_weight="balanced", gamma="scale", C=10)  # Use best params from GridSearchCV
svm_tfidf_withoutStopwords_RemovePunctuation.fit(X_train, y_train)
svm_tfidf_withoutStopwords_RemovePunctuation_pred = svm_tfidf_withoutStopwords_RemovePunctuation.predict(X_test)

print(classification_report(y_test, svm_tfidf_withoutStopwords_RemovePunctuation_pred))

              precision    recall  f1-score   support

    negative       0.76      0.76      0.76       418
     neutral       0.65      0.68      0.66       401
    positive       0.82      0.79      0.81       431

    accuracy                           0.74      1250
   macro avg       0.74      0.74      0.74      1250
weighted avg       0.75      0.74      0.74      1250



In [39]:
print("TF-IDF Cleaned SVM F1 Score:", f1_score(y_test, svm_tfidf_withoutStopwords_RemovePunctuation_pred, average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(y_test, svm_tfidf_withoutStopwords_RemovePunctuation_pred, average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(y_test, svm_tfidf_withoutStopwords_RemovePunctuation_pred, average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(y_test, svm_tfidf_withoutStopwords_RemovePunctuation_pred))   

TF-IDF Cleaned SVM F1 Score: 0.7441514493935685
TF-IDF Cleaned SVM Precision: 0.7454635443503864
TF-IDF Cleaned SVM Recall: 0.7432
TF-IDF Cleaned SVM Accuracy Score: 0.7432


### Linear Regression with TF-IDF Cleaned

In [29]:
df_feat = pd.read_csv("text_representation/TF_IDF/text_representation_cleaned_tfidf.xls")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

mapping = {
    "negative": -1,
    "neutral": 0,
    "positive": 1
    }
df_feat["sentiment"] = df_labels["sentiment"]
df_feat["sentiment"] = df_feat["sentiment"].map(mapping)

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define model
ln_reg = LinearRegression()

# Define parameter grid
param_grid = {
    "fit_intercept": [True, False],
    "positive": [True, False]
}

# Use regression metric
scorer = make_scorer(mean_squared_error, greater_is_better=False)

# Grid Search
grid = GridSearchCV(
    estimator=ln_reg,
    param_grid=param_grid,
    scoring=scorer,
    cv=5,
    n_jobs=-1,
    verbose=2
)

# Fit on training data only
grid.fit(X_train, y_train)

# Best model
best_model = grid.best_estimator_

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best Params: {'fit_intercept': True, 'positive': False}
Best CV Score: -0.5006255009898367


In [30]:
df_feat = pd.read_csv("text_representation/TF_IDF/text_representation_cleaned_tfidf.xls")
df_labels = pd.read_csv("schemas/fully_cleaned.csv")
# Merge features and labels
mapping = {
"negative": -1,
"neutral": 0,
"positive": 1
}
df_feat["sentiment"] = df_labels["sentiment"]
df_feat["sentiment"] = df_feat["sentiment"].map(mapping)

X = df_feat.drop("sentiment", axis=1)
y = df_feat["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# -------- Linear Regression --------
ln_reg = LinearRegression(fit_intercept=True, positive=False)  # Use best params from GridSearchCV
ln_reg.fit(X_train, y_train)
ln_pred = ln_reg.predict(X_test)
def convert_to_class(x):
    if x > 0.5:
        return "positive"
    elif x < -0.5:
        return "negative"
    else:
        return "neutral"

ln_pred_class = [convert_to_class(x) for x in ln_pred]
y_test_class = [convert_to_class(x) for x in y_test]


print(classification_report(y_test_class, ln_pred_class))

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         2
     neutral       1.00      0.33      0.50         3
    positive       0.56      1.00      0.71         5

    accuracy                           0.60        10
   macro avg       0.52      0.44      0.40        10
weighted avg       0.58      0.60      0.51        10



In [31]:
print("TF-IDF Cleaned Linear regression F1 Score:,", f1_score(y_test_class, ln_pred_class, average='weighted'))
print("TF-IDF Cleaned Linear regression Precision:", precision_score(y_test_class, ln_pred_class, average='weighted'))
print("TF-IDF Cleaned Linear regression Recall:", recall_score(y_test_class, ln_pred_class, average='weighted'))
print("TF-IDF Cleaned Linear regression Accuracy Score:", accuracy_score(y_test_class, ln_pred_class))

TF-IDF Cleaned Linear regression F1 Score:, 0.5071428571428571
TF-IDF Cleaned Linear regression Precision: 0.5777777777777777
TF-IDF Cleaned Linear regression Recall: 0.6
TF-IDF Cleaned Linear regression Accuracy Score: 0.6


In [ ]:
import pickle
model_path = "model/SVM_tfidf_cleaned_balanced.pkl"
with open(model_path, "wb") as f:
    pickle.dump(svm_tfidf, f)
print(f"Saved model to {model_path}")

Saved model to model/SVM_tfidf_cleaned_balanced.pkl


In [40]:
model_path = "model/SVM_tfidf_with_stopwords.pkl"
with open(model_path, "wb") as f:
    pickle.dump(svm_tfidf_withoutStopwords_RemovePunctuation, f)
print(f"Saved model to {model_path}")

Saved model to model/SVM_tfidf_with_stopwords.pkl


In [14]:
X = load_npz("text_representation/TF_IDF/text_representation_cleaned_tfidf.npz")
X.data = np.round(X.data, 3)
df_labels = pd.read_csv("schemas/fully_cleaned.csv")

y = df_labels["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = re.sub(r'<[^>]+>', ' ', text)     # Remove HTML tags (like <br>)
    text = re.sub(r'http[s]?://\S+', '', text) # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text) # Remove URLs
    text = re.sub(r'\s+', ' ', text).strip()   # Remove extra spaces/newlines
    text = text.translate(str.maketrans('', '', string.punctuation)) # Remove punctuation
    text = text.lower() # Convert to lowercase
    text = " ".join([word for word in text.split() if word not in stop]) # Remove stop words
    text = re.sub(r'\d+', '', text) # Remove numbers
    # text = re.sub(r'[^\w\s]', '', text) # Remove special characters
    text = re.sub(r'\s+', ' ', text).strip() # Remove extra spaces again after all cleaning
    text = re.sub(r'\b\w\b', '', text) # Remove single characters
    text = re.sub(r'@\w+', '', text) # Remove mentions
    text = re.sub(r'#\w+', '', text) # Remove hashtags
    text = re.sub(r'&\w+;', ' ', text) # Remove HTML entities
    # add lemmatization
    text = " ".join([lemmatizer.lemmatize(word) for word in text.split()])
    return text

# test the saved model
with open(model_path, "rb") as f:
    loaded_model = pickle.load(f)

# load victorizer and transform test data
with open("model/text_representation_cleaned_tfidf_vectorizer.pkl", "rb") as f:
    loaded_vectorizer = pickle.load(f)
    
test = "it is very bad movie, I hated it!"
test = loaded_vectorizer.transform([clean_text(test)])
loaded_pred = loaded_model.predict(X_test)
print("Predicted class for test input:", loaded_pred[0])

Predicted class for test input: neutral


In [15]:
loaded_pred = loaded_model.predict(X_test)
# metrics
print(classification_report(y_test, loaded_pred))
print("TF-IDF Cleaned SVM F1 Score:", f1_score(y_test, loaded_pred, average='weighted'))
print("TF-IDF Cleaned SVM Precision:", precision_score(y_test, loaded_pred, average='weighted'))
print("TF-IDF Cleaned SVM Recall:", recall_score(y_test, loaded_pred, average='weighted'))
print("TF-IDF Cleaned SVM Accuracy Score:", accuracy_score(y_test, loaded_pred))


              precision    recall  f1-score   support

    negative       0.75      0.56      0.64       186
     neutral       0.66      0.71      0.68       394
    positive       0.88      0.90      0.89      1153

    accuracy                           0.82      1733
   macro avg       0.77      0.72      0.74      1733
weighted avg       0.82      0.82      0.82      1733

TF-IDF Cleaned SVM F1 Score: 0.8157800765682336
TF-IDF Cleaned SVM Precision: 0.8174181568549909
TF-IDF Cleaned SVM Recall: 0.8176572417772648
TF-IDF Cleaned SVM Accuracy Score: 0.8176572417772648
